import { EventDetails } from '../models/events/event-details.model';

export const TARGET_ADMIN_EVENTS: EventDetails[] = [
  // Page 1 (Matching Image 2 exactly)
  {
    id: 2,
    name: 'Rockstar Aniruth Musical Show - 2026',
    posterUrl: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2026-09-12',
    startTime: '12:00:00',
    endTime: '16:30:00',
    ticketPrice: 5000,
    childDiscountPercent: 0,
    venueId: 2,
    venueName: 'Unicom TIC, Jaffna',
    categoryId: 2,
    categoryName: 'Music Concert',
    capacity: 624,
    totalSeats: 624,
    availableSeats: 340,
    bookedSeats: 284,
    soldPercentage: 45.5,
    hasBookings: true,
    canDelete: false,
    description: 'Get ready for an unforgettable night as Rockstar Aniruth takes the stage in 2026 with a power-packed live musical show! Experience chart-topping hits, stunning visuals, and an unmatched atmosphere that only a live concert can deliver.',
    stageLayout: 'Circular Arena',
    venueAddress: 'Unicom TIC, Jaffna',
    venueCapacity: 624,
    bookingCount: 284,
    canEditTicketPrice: false,
    canEditCapacity: false,
    canEditStageLayout: false
  },
  {
    id: 102,
    name: 'Global AI Summit 2026',
    posterUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2026-10-03',
    startTime: '09:00:00',
    endTime: '17:00:00',
    ticketPrice: 3500,
    childDiscountPercent: 0,
    venueId: 5,
    venueName: 'Cinnamon Life, Colombo',
    categoryId: 5,
    categoryName: 'Technology',
    capacity: 500,
    totalSeats: 500,
    availableSeats: 302,
    bookedSeats: 198,
    soldPercentage: 39.6,
    hasBookings: true,
    canDelete: false,
    description: 'Connect with global tech leaders, AI innovators, and developers shaping next-generation intelligence, LLMs, and cloud infrastructure.',
    stageLayout: 'Keynote Auditorium',
    venueAddress: 'Cinnamon Life, Colombo',
    venueCapacity: 500,
    bookingCount: 198,
    canEditTicketPrice: false,
    canEditCapacity: false,
    canEditStageLayout: false
  },
  {
    id: 103,
    name: 'Tamil Cultural Night 2026',
    posterUrl: 'https://images.unsplash.com/photo-1607998803461-4e9aef3be418?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2026-10-17',
    startTime: '18:00:00',
    endTime: '21:30:00',
    ticketPrice: 2500,
    childDiscountPercent: 0,
    venueId: 7,
    venueName: 'Jaffna Cultural Centre',
    categoryId: 8,
    categoryName: 'Cultural',
    capacity: 360,
    totalSeats: 360,
    availableSeats: 214,
    bookedSeats: 146,
    soldPercentage: 40.5,
    hasBookings: true,
    canDelete: false,
    description: 'A celebration of traditional music, classical dance, and vibrant folk performances showcasing the timeless heritage of Northern Sri Lanka.',
    stageLayout: 'Amphitheatre',
    venueAddress: 'Jaffna Cultural Centre',
    venueCapacity: 360,
    bookingCount: 146,
    canEditTicketPrice: false,
    canEditCapacity: false,
    canEditStageLayout: false
  },
  {
    id: 104,
    name: 'Startup Expo 2026',
    posterUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2026-11-05',
    startTime: '09:30:00',
    endTime: '16:30:00',
    ticketPrice: 2000,
    childDiscountPercent: 0,
    venueId: 8,
    venueName: 'City Hall, Kandy',
    categoryId: 9,
    categoryName: 'Business & Networking',
    capacity: 450,
    totalSeats: 450,
    availableSeats: 450,
    bookedSeats: 0,
    soldPercentage: 0,
    hasBookings: false,
    canDelete: true,
    description: 'Leading platform showcasing high-growth ventures, seed-funded startups, and tech incubators across Sri Lanka.',
    stageLayout: 'Exhibition Hall',
    venueAddress: 'City Hall, Kandy',
    venueCapacity: 450,
    bookingCount: 0,
    canEditTicketPrice: true,
    canEditCapacity: true,
    canEditStageLayout: true
  },
  {
    id: 105,
    name: 'Education Future Forum',
    posterUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2026-11-20',
    startTime: '10:00:00',
    endTime: '16:00:00',
    ticketPrice: 1500,
    childDiscountPercent: 0,
    venueId: 9,
    venueName: 'BMICH Main Hall, Colombo',
    categoryId: 10,
    categoryName: 'Education',
    capacity: 700,
    totalSeats: 700,
    availableSeats: 700,
    bookedSeats: 0,
    soldPercentage: 0,
    hasBookings: false,
    canDelete: true,
    description: 'Exploring tomorrow\'s learning models, advanced STEM research, and educational technology for future generations.',
    stageLayout: 'Concentric Hall',
    venueAddress: 'BMICH Main Hall, Colombo',
    venueCapacity: 700,
    bookingCount: 0,
    canEditTicketPrice: true,
    canEditCapacity: true,
    canEditStageLayout: true
  },
  {
    id: 106,
    name: 'Live Music Festival 2026',
    posterUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2026-12-06',
    startTime: '17:00:00',
    endTime: '23:00:00',
    ticketPrice: 4500,
    childDiscountPercent: 0,
    venueId: 5,
    venueName: 'Cinnamon Life, Colombo',
    categoryId: 2,
    categoryName: 'Music Concert',
    capacity: 800,
    totalSeats: 800,
    availableSeats: 800,
    bookedSeats: 0,
    soldPercentage: 0,
    hasBookings: false,
    canDelete: true,
    description: 'Electrifying open-air live music festival with renowned bands and sensational visual production.',
    stageLayout: 'Open Air Arena',
    venueAddress: 'Cinnamon Life, Colombo',
    venueCapacity: 800,
    bookingCount: 0,
    canEditTicketPrice: true,
    canEditCapacity: true,
    canEditStageLayout: true
  },

  // Page 2 (Events 7-12)
  {
    id: 107,
    name: 'Colombo Tech Week 2026',
    posterUrl: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2026-12-15',
    startTime: '09:00:00',
    endTime: '18:00:00',
    ticketPrice: 6000,
    childDiscountPercent: 0,
    venueId: 5,
    venueName: 'Cinnamon Life, Colombo',
    categoryId: 5,
    categoryName: 'Technology',
    capacity: 600,
    totalSeats: 600,
    availableSeats: 480,
    bookedSeats: 120,
    soldPercentage: 20,
    hasBookings: true,
    canDelete: false,
    description: 'A comprehensive week of technical keynotes, hackathons, and product launches from global engineering leaders.',
    stageLayout: 'Grand Ballroom',
    venueAddress: 'Cinnamon Life, Colombo',
    venueCapacity: 600,
    bookingCount: 120,
    canEditTicketPrice: false,
    canEditCapacity: false,
    canEditStageLayout: false
  },
  {
    id: 108,
    name: 'Sri Lanka vs Australia ODI',
    posterUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2026-12-22',
    startTime: '14:00:00',
    endTime: '22:00:00',
    ticketPrice: 4000,
    childDiscountPercent: 0,
    venueId: 3,
    venueName: 'Sugathadasa Indoor Stadium',
    categoryId: 3,
    categoryName: 'Sports & Fitness',
    capacity: 5000,
    totalSeats: 5000,
    availableSeats: 3600,
    bookedSeats: 1400,
    soldPercentage: 28,
    hasBookings: true,
    canDelete: false,
    description: 'Day-night cricket showdown in front of an enthusiastic capacity crowd with premium stadium hospitality.',
    stageLayout: 'Stadium Seating',
    venueAddress: 'Sugathadasa Indoor Stadium, Colombo',
    venueCapacity: 5000,
    bookingCount: 1400,
    canEditTicketPrice: false,
    canEditCapacity: false,
    canEditStageLayout: false
  },
  {
    id: 109,
    name: 'Symphony Orchestra Gala',
    posterUrl: 'https://images.unsplash.com/photo-1469488865564-c2de10f69f96?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2026-12-28',
    startTime: '19:00:00',
    endTime: '22:00:00',
    ticketPrice: 7500,
    childDiscountPercent: 0,
    venueId: 4,
    venueName: 'Nelum Pokuna Mahinda Rajapaksa Theatre',
    categoryId: 2,
    categoryName: 'Music Concert',
    capacity: 1288,
    totalSeats: 1288,
    availableSeats: 980,
    bookedSeats: 308,
    soldPercentage: 23.9,
    hasBookings: true,
    canDelete: false,
    description: 'Classical symphony gala performing Beethoven, Mozart, and modern cinematic orchestrations.',
    stageLayout: 'Proscenium Theatre',
    venueAddress: '110 Ananda Coomaraswamy Mawatha, Colombo 07',
    venueCapacity: 1288,
    bookingCount: 308,
    canEditTicketPrice: false,
    canEditCapacity: false,
    canEditStageLayout: false
  },
  {
    id: 110,
    name: 'New Year Countdown Fiesta',
    posterUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2026-12-31',
    startTime: '20:00:00',
    endTime: '02:00:00',
    ticketPrice: 8000,
    childDiscountPercent: 0,
    venueId: 1,
    venueName: 'EventFlow Main Hall',
    categoryId: 2,
    categoryName: 'Music Concert',
    capacity: 1500,
    totalSeats: 1500,
    availableSeats: 1100,
    bookedSeats: 400,
    soldPercentage: 26.6,
    hasBookings: true,
    canDelete: false,
    description: 'Celebrate the grand countdown to 2027 with top international DJs, live countdown, and fireworks.',
    stageLayout: 'Concert Stage',
    venueAddress: 'EventFlow Main Hall, Colombo',
    venueCapacity: 1500,
    bookingCount: 400,
    canEditTicketPrice: false,
    canEditCapacity: false,
    canEditStageLayout: false
  },
  {
    id: 111,
    name: 'Fintech Revolution Summit',
    posterUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2027-01-14',
    startTime: '09:00:00',
    endTime: '17:00:00',
    ticketPrice: 3000,
    childDiscountPercent: 0,
    venueId: 9,
    venueName: 'BMICH Main Hall, Colombo',
    categoryId: 9,
    categoryName: 'Business & Networking',
    capacity: 450,
    totalSeats: 450,
    availableSeats: 450,
    bookedSeats: 0,
    soldPercentage: 0,
    hasBookings: false,
    canDelete: true,
    description: 'Exploring payments modernization, open banking APIs, and financial inclusion across South Asia.',
    stageLayout: 'Executive Suite',
    venueAddress: 'BMICH Main Hall, Colombo',
    venueCapacity: 450,
    bookingCount: 0,
    canEditTicketPrice: true,
    canEditCapacity: true,
    canEditStageLayout: true
  },
  {
    id: 112,
    name: 'National Badminton Championship',
    posterUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2027-01-20',
    startTime: '10:00:00',
    endTime: '18:00:00',
    ticketPrice: 1200,
    childDiscountPercent: 0,
    venueId: 3,
    venueName: 'Sugathadasa Indoor Stadium',
    categoryId: 3,
    categoryName: 'Sports & Fitness',
    capacity: 1200,
    totalSeats: 1200,
    availableSeats: 1200,
    bookedSeats: 0,
    soldPercentage: 0,
    hasBookings: false,
    canDelete: true,
    description: 'The top national shuttlers compete in championship matches across singles, doubles, and mixed brackets.',
    stageLayout: 'Court Complex',
    venueAddress: 'Sugathadasa Indoor Stadium, Colombo',
    venueCapacity: 1200,
    bookingCount: 0,
    canEditTicketPrice: true,
    canEditCapacity: true,
    canEditStageLayout: true
  },

  // Page 3 (Events 13-18)
  {
    id: 113,
    name: 'Contemporary Dance Showcase',
    posterUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2027-02-05',
    startTime: '18:30:00',
    endTime: '21:00:00',
    ticketPrice: 1800,
    childDiscountPercent: 0,
    venueId: 7,
    venueName: 'Jaffna Cultural Centre',
    categoryId: 8,
    categoryName: 'Cultural',
    capacity: 360,
    totalSeats: 360,
    availableSeats: 360,
    bookedSeats: 0,
    soldPercentage: 0,
    hasBookings: false,
    canDelete: true,
    description: 'Expressive contemporary choreography merging classical South Asian traditions with experimental modern movement.',
    stageLayout: 'Amphitheatre',
    venueAddress: 'Jaffna Cultural Centre',
    venueCapacity: 360,
    bookingCount: 0,
    canEditTicketPrice: true,
    canEditCapacity: true,
    canEditStageLayout: true
  },
  {
    id: 114,
    name: 'Healthcare Innovation Congress',
    posterUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2027-02-18',
    startTime: '09:00:00',
    endTime: '17:00:00',
    ticketPrice: 2500,
    childDiscountPercent: 0,
    venueId: 9,
    venueName: 'BMICH Main Hall, Colombo',
    categoryId: 10,
    categoryName: 'Education',
    capacity: 500,
    totalSeats: 500,
    availableSeats: 500,
    bookedSeats: 0,
    soldPercentage: 0,
    hasBookings: false,
    canDelete: true,
    description: 'Medical professionals and biotech researchers gathering to discuss genomics, telemedicine, and healthcare AI.',
    stageLayout: 'Concentric Hall',
    venueAddress: 'BMICH Main Hall, Colombo',
    venueCapacity: 500,
    bookingCount: 0,
    canEditTicketPrice: true,
    canEditCapacity: true,
    canEditStageLayout: true
  },
  {
    id: 115,
    name: 'Design & UX Horizons 2027',
    posterUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2027-03-02',
    startTime: '10:00:00',
    endTime: '17:00:00',
    ticketPrice: 3200,
    childDiscountPercent: 0,
    venueId: 8,
    venueName: 'City Hall, Kandy',
    categoryId: 5,
    categoryName: 'Technology',
    capacity: 400,
    totalSeats: 400,
    availableSeats: 400,
    bookedSeats: 0,
    soldPercentage: 0,
    hasBookings: false,
    canDelete: true,
    description: 'Design leaders dissecting user interface craftsmanship, spatial design, and accessible computing.',
    stageLayout: 'Workshop Hall',
    venueAddress: 'City Hall, Kandy',
    venueCapacity: 400,
    bookingCount: 0,
    canEditTicketPrice: true,
    canEditCapacity: true,
    canEditStageLayout: true
  },
  {
    id: 116,
    name: 'International Jazz Quintet',
    posterUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2027-03-15',
    startTime: '19:30:00',
    endTime: '22:30:00',
    ticketPrice: 5500,
    childDiscountPercent: 0,
    venueId: 4,
    venueName: 'Nelum Pokuna Mahinda Rajapaksa Theatre',
    categoryId: 2,
    categoryName: 'Music Concert',
    capacity: 850,
    totalSeats: 850,
    availableSeats: 850,
    bookedSeats: 0,
    soldPercentage: 0,
    hasBookings: false,
    canDelete: true,
    description: 'An intimate evening of syncopated rhythms, saxophone solos, and sublime jazz improvisation.',
    stageLayout: 'Proscenium Theatre',
    venueAddress: '110 Ananda Coomaraswamy Mawatha, Colombo 07',
    venueCapacity: 850,
    bookingCount: 0,
    canEditTicketPrice: true,
    canEditCapacity: true,
    canEditStageLayout: true
  },
  {
    id: 117,
    name: 'Island Youth Drama Festival',
    posterUrl: 'https://images.unsplash.com/photo-1469488865564-c2de10f69f96?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2027-03-26',
    startTime: '17:00:00',
    endTime: '21:00:00',
    ticketPrice: 1000,
    childDiscountPercent: 0,
    venueId: 7,
    venueName: 'Jaffna Cultural Centre',
    categoryId: 4,
    categoryName: 'Theatre & Arts',
    capacity: 360,
    totalSeats: 360,
    availableSeats: 360,
    bookedSeats: 0,
    soldPercentage: 0,
    hasBookings: false,
    canDelete: true,
    description: 'Original theatrical plays staged by youth drama troupes, featuring satire, historical fiction, and monologues.',
    stageLayout: 'Amphitheatre',
    venueAddress: 'Jaffna Cultural Centre',
    venueCapacity: 360,
    bookingCount: 0,
    canEditTicketPrice: true,
    canEditCapacity: true,
    canEditStageLayout: true
  },
  {
    id: 118,
    name: 'Green Energy & Sustainability Expo',
    posterUrl: 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2027-04-08',
    startTime: '09:30:00',
    endTime: '17:30:00',
    ticketPrice: 1500,
    childDiscountPercent: 0,
    venueId: 1,
    venueName: 'EventFlow Main Hall',
    categoryId: 9,
    categoryName: 'Business & Networking',
    capacity: 900,
    totalSeats: 900,
    availableSeats: 900,
    bookedSeats: 0,
    soldPercentage: 0,
    hasBookings: false,
    canDelete: true,
    description: 'Clean energy technologies, solar grid innovations, electric mobility, and environmental preservation workshops.',
    stageLayout: 'Exhibition Hall',
    venueAddress: 'EventFlow Main Hall, Colombo',
    venueCapacity: 900,
    bookingCount: 0,
    canEditTicketPrice: true,
    canEditCapacity: true,
    canEditStageLayout: true
  },

  // Page 4 (Events 19-24 - Past events)
  {
    id: 119,
    name: 'Summer Rock Night 2026',
    posterUrl: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2026-08-15',
    startTime: '19:00:00',
    endTime: '23:00:00',
    ticketPrice: 3500,
    childDiscountPercent: 0,
    venueId: 2,
    venueName: 'Unicom TIC, Jaffna',
    categoryId: 2,
    categoryName: 'Music Concert',
    capacity: 600,
    totalSeats: 600,
    availableSeats: 0,
    bookedSeats: 600,
    soldPercentage: 100,
    hasBookings: true,
    canDelete: false,
    description: 'Past summer concert with headline rock and metal artists performing to an ecstatic sold-out arena.',
    stageLayout: 'Circular Arena',
    venueAddress: 'Unicom TIC, Jaffna',
    venueCapacity: 600,
    bookingCount: 600,
    canEditTicketPrice: false,
    canEditCapacity: false,
    canEditStageLayout: false
  },
  {
    id: 120,
    name: 'Sri Lanka Open Chess Masters',
    posterUrl: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2026-07-20',
    startTime: '09:00:00',
    endTime: '18:00:00',
    ticketPrice: 1000,
    childDiscountPercent: 0,
    venueId: 8,
    venueName: 'City Hall, Kandy',
    categoryId: 3,
    categoryName: 'Sports & Fitness',
    capacity: 250,
    totalSeats: 250,
    availableSeats: 0,
    bookedSeats: 250,
    soldPercentage: 100,
    hasBookings: true,
    canDelete: false,
    description: 'FIDE-rated international chess tournament bringing Grandmasters and top national players together.',
    stageLayout: 'Tournament Hall',
    venueAddress: 'City Hall, Kandy',
    venueCapacity: 250,
    bookingCount: 250,
    canEditTicketPrice: false,
    canEditCapacity: false,
    canEditStageLayout: false
  },
  {
    id: 121,
    name: 'Robotics Champions League',
    posterUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2026-06-10',
    startTime: '10:00:00',
    endTime: '17:00:00',
    ticketPrice: 2000,
    childDiscountPercent: 0,
    venueId: 9,
    venueName: 'BMICH Main Hall, Colombo',
    categoryId: 5,
    categoryName: 'Technology',
    capacity: 650,
    totalSeats: 650,
    availableSeats: 0,
    bookedSeats: 650,
    soldPercentage: 100,
    hasBookings: true,
    canDelete: false,
    description: 'Autonomous combat robots, maze navigators, and drone racers competing in national finals.',
    stageLayout: 'Arena Layout',
    venueAddress: 'BMICH Main Hall, Colombo',
    venueCapacity: 650,
    bookingCount: 650,
    canEditTicketPrice: false,
    canEditCapacity: false,
    canEditStageLayout: false
  },
  {
    id: 122,
    name: 'Classical Carnatic Recital',
    posterUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2026-05-25',
    startTime: '18:00:00',
    endTime: '21:00:00',
    ticketPrice: 1500,
    childDiscountPercent: 0,
    venueId: 7,
    venueName: 'Jaffna Cultural Centre',
    categoryId: 8,
    categoryName: 'Cultural',
    capacity: 360,
    totalSeats: 360,
    availableSeats: 0,
    bookedSeats: 360,
    soldPercentage: 100,
    hasBookings: true,
    canDelete: false,
    description: 'Enthralling vocal and veena recital exploring traditional ragas by veteran Carnatic maestros.',
    stageLayout: 'Amphitheatre',
    venueAddress: 'Jaffna Cultural Centre',
    venueCapacity: 360,
    bookingCount: 360,
    canEditTicketPrice: false,
    canEditCapacity: false,
    canEditStageLayout: false
  },
  {
    id: 123,
    name: 'Asian Business Leadership Forum',
    posterUrl: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2026-04-18',
    startTime: '08:30:00',
    endTime: '17:00:00',
    ticketPrice: 5000,
    childDiscountPercent: 0,
    venueId: 5,
    venueName: 'Cinnamon Life, Colombo',
    categoryId: 9,
    categoryName: 'Business & Networking',
    capacity: 500,
    totalSeats: 500,
    availableSeats: 0,
    bookedSeats: 500,
    soldPercentage: 100,
    hasBookings: true,
    canDelete: false,
    description: 'High-profile gathering of CEOs, policymakers, and corporate strategists discussing regional economic growth.',
    stageLayout: 'Summit Hall',
    venueAddress: 'Cinnamon Life, Colombo',
    venueCapacity: 500,
    bookingCount: 500,
    canEditTicketPrice: false,
    canEditCapacity: false,
    canEditStageLayout: false
  },
  {
    id: 124,
    name: 'Spring Broadway Fantasy',
    posterUrl: 'https://images.unsplash.com/photo-1469488865564-c2de10f69f96?auto=format&fit=crop&w=1000&q=80',
    eventDate: '2026-03-12',
    startTime: '18:30:00',
    endTime: '21:30:00',
    ticketPrice: 6000,
    childDiscountPercent: 0,
    venueId: 4,
    venueName: 'Nelum Pokuna Mahinda Rajapaksa Theatre',
    categoryId: 4,
    categoryName: 'Theatre & Arts',
    capacity: 1200,
    totalSeats: 1200,
    availableSeats: 0,
    bookedSeats: 1200,
    soldPercentage: 100,
    hasBookings: true,
    canDelete: false,
    description: 'Celebrated spring broadway musical tribute featuring timeless songs and dazzling costume choreography.',
    stageLayout: 'Proscenium Theatre',
    venueAddress: '110 Ananda Coomaraswamy Mawatha, Colombo 07',
    venueCapacity: 1200,
    bookingCount: 1200,
    canEditTicketPrice: false,
    canEditCapacity: false,
    canEditStageLayout: false
  }
];
