// <auto-generated />
using System;
using EventParkingReservationSystem.API.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventParkingReservationSystem.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260917005342_SeedAccurateEventDetails")]
    partial class SeedAccurateEventDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Bookings.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("BookingNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HoldExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingNumber")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("EventId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Bookings.BookingSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttendeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AttendeeType")
                        .HasColumnType("int");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("BookingId", "SeatId")
                        .IsUnique();

                    b.ToTable("BookingSeats");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Categories.EventCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EventCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Concert",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Concerts & Music",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sports & Fitness",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Theatre & Arts",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Conferences & Seminars",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Expos & Trade Shows",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Customers.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("EmailVerificationTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailVerificationTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Customers.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonRevoked")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Events.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("ChildDiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StageLayout")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<decimal>("TicketPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EventDate");

                    b.HasIndex("VenueId", "EventDate");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 5000,
                            CategoryId = 2,
                            ChildDiscountPercent = 50m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Experience an electrifying evening with chartbuster hits and a spectacular live production featuring Anirudh Ravichander live in concert at Colombo's premier indoor stadium.",
                            EndTime = new TimeOnly(23, 30, 0),
                            EventDate = new DateOnly(2026, 10, 18),
                            Name = "Anirudh Live in Colombo 2026",
                            PosterUrl = "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80",
                            StageLayout = "Indoor Arena",
                            StartTime = new TimeOnly(20, 0, 0),
                            TicketPrice = 4500m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VenueId = 3
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 624,
                            CategoryId = 2,
                            ChildDiscountPercent = 50m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Get ready for an unforgettable night as Rockstar Aniruth takes the stage in 2026 with a power-packed live musical show! Experience chart-topping hits, stunning visuals, and an unmatched atmosphere that only a live concert can deliver.\n\nThis is a major live music event designed for a premium audience experience. Your booking includes access to the available Platinum, Gold, and Silver sections. VIP Pre-Reserved seats are not available for normal customer booking.",
                            EndTime = new TimeOnly(16, 30, 0),
                            EventDate = new DateOnly(2026, 9, 25),
                            Name = "Rockstar Aniruth Musical Show - 2026",
                            PosterUrl = "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?auto=format&fit=crop&w=1200&q=80",
                            StageLayout = "Circular Arena",
                            StartTime = new TimeOnly(12, 0, 0),
                            TicketPrice = 10000m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VenueId = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 5000,
                            CategoryId = 3,
                            ChildDiscountPercent = 50m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The ultimate cricket rivalry reignites under the stadium floodlights. Watch the giants battle in an epic high-stakes T20 international encounter with world-class seating and hospitality.",
                            EndTime = new TimeOnly(23, 0, 0),
                            EventDate = new DateOnly(2026, 10, 28),
                            Name = "Sri Lanka vs India T20 Showdown",
                            PosterUrl = "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1200&q=80",
                            StageLayout = "Stadium Seating",
                            StartTime = new TimeOnly(19, 0, 0),
                            TicketPrice = 3500m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VenueId = 3
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 1288,
                            CategoryId = 4,
                            ChildDiscountPercent = 40m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The legendary Broadway masterpiece arrives with full orchestral arrangements, magnificent sets, and transcendent vocal performances in Sri Lanka's finest auditorium.",
                            EndTime = new TimeOnly(20, 30, 0),
                            EventDate = new DateOnly(2026, 11, 5),
                            Name = "The Phantom of the Opera Musical",
                            PosterUrl = "https://images.unsplash.com/photo-1469488865564-c2de10f69f96?auto=format&fit=crop&w=1200&q=80",
                            StageLayout = "Proscenium Theatre",
                            StartTime = new TimeOnly(17, 0, 0),
                            TicketPrice = 7500m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VenueId = 4
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 2000,
                            CategoryId = 5,
                            ChildDiscountPercent = 0m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Connect with global tech leaders, keynote innovators, and developers shaping next-generation AI and cloud architecture. Three days of cutting-edge keynotes and technical workshops.",
                            EndTime = new TimeOnly(17, 0, 0),
                            EventDate = new DateOnly(2026, 10, 12),
                            Name = "Global Tech Summit 2026",
                            PosterUrl = "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80",
                            StageLayout = "Keynote Auditorium",
                            StartTime = new TimeOnly(9, 0, 0),
                            TicketPrice = 7950m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VenueId = 5
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 3000,
                            CategoryId = 6,
                            ChildDiscountPercent = 50m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The premier construction, architecture, and engineering exhibition showcasing innovative green technologies, modern materials, and smart building solutions for South Asia.",
                            EndTime = new TimeOnly(18, 0, 0),
                            EventDate = new DateOnly(2026, 11, 8),
                            Name = "Sri Lanka Build Expo 2026",
                            PosterUrl = "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80",
                            StageLayout = "Exhibition Hall",
                            StartTime = new TimeOnly(10, 0, 0),
                            TicketPrice = 1200m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VenueId = 5
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 1500,
                            CategoryId = 5,
                            ChildDiscountPercent = 0m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An inspiring gathering of visionaries, product strategists, and creative executives exploring design excellence, future-forward brand building, and storytelling.",
                            EndTime = new TimeOnly(16, 30, 0),
                            EventDate = new DateOnly(2026, 10, 24),
                            Name = "Creative Leaders Summit 2026",
                            PosterUrl = "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80",
                            StageLayout = "Grand Ballroom",
                            StartTime = new TimeOnly(9, 0, 0),
                            TicketPrice = 1800m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VenueId = 6
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 1000,
                            CategoryId = 2,
                            ChildDiscountPercent = 50m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A celebration of traditional music, classical dance, and vibrant folk performances showcasing the timeless heritage and art of Northern Sri Lanka.",
                            EndTime = new TimeOnly(21, 30, 0),
                            EventDate = new DateOnly(2026, 11, 18),
                            Name = "Tamil Cultural Night 2026",
                            PosterUrl = "https://images.unsplash.com/photo-1607998803461-4e9aef3be418?auto=format&fit=crop&w=1200&q=80",
                            StageLayout = "Amphitheatre",
                            StartTime = new TimeOnly(18, 30, 0),
                            TicketPrice = 1000m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VenueId = 7
                        });
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Notifications.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NotificationId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Parking.ParkingSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("ParkingZoneId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PositionX")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PositionY")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SlotCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParkingZoneId");

                    b.HasIndex("EventId", "SlotCode")
                        .IsUnique();

                    b.ToTable("ParkingSlots");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Parking.ParkingZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<decimal>("Fee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsOnlineBookable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Name")
                        .IsUnique();

                    b.ToTable("ParkingZones");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.ParkingReservations.ParkingReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal>("FeeSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ParkingSlotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleTypeSnapshot")
                        .HasColumnType("int");

                    b.Property<string>("ZoneNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("ParkingSlotId");

                    b.ToTable("ParkingReservations");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Payments.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("LKR");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Seats.EventSeatCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdultPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPubliclyBookable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Code")
                        .IsUnique();

                    b.ToTable("EventSeatCategories");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Seats.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<decimal?>("PositionX")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PositionY")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RowLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SeatCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SeatSectionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatSectionId");

                    b.HasIndex("EventId", "SeatCode")
                        .IsUnique();

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Seats.SeatSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("EventSeatCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EventSeatCategoryId");

                    b.HasIndex("EventId", "Code")
                        .IsUnique();

                    b.ToTable("SeatSections");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Venues.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Venues", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Colombo, Sri Lanka",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "EventFlow Main Hall",
                            TotalCapacity = 1500,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Address = "A9 Road, Jaffna, Sri Lanka",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Unicom TIC",
                            TotalCapacity = 2500,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Prince of Wales Ave, Colombo 14, Sri Lanka",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sugathadasa Indoor Stadium",
                            TotalCapacity = 5000,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Address = "110 Ananda Coomaraswamy Mawatha, Colombo 07, Sri Lanka",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Nelum Pokuna Mahinda Rajapaksa Theatre",
                            TotalCapacity = 1288,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Bauddhaloka Mawatha, Colombo 07, Sri Lanka",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "BMICH, Colombo",
                            TotalCapacity = 3000,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Address = "1 Justice Akbar Mawatha, Colombo 02, Sri Lanka",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cinnamon Life, Colombo",
                            TotalCapacity = 1500,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Address = "Mahatma Gandhi Road, Jaffna, Sri Lanka",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Jaffna Cultural Centre",
                            TotalCapacity = 1000,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Bookings.Booking", b =>
                {
                    b.HasOne("EventParkingReservationSystem.API.Models.Entities.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventParkingReservationSystem.API.Models.Entities.Events.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Bookings.BookingSeat", b =>
                {
                    b.HasOne("EventParkingReservationSystem.API.Models.Entities.Bookings.Booking", "Booking")
                        .WithMany("BookingSeats")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventParkingReservationSystem.API.Models.Entities.Seats.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Customers.RefreshToken", b =>
                {
                    b.HasOne("EventParkingReservationSystem.API.Models.Entities.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Events.Event", b =>
                {
                    b.HasOne("EventParkingReservationSystem.API.Models.Entities.Categories.EventCategory", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventParkingReservationSystem.API.Models.Entities.Venues.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Notifications.Notification", b =>
                {
                    b.HasOne("EventParkingReservationSystem.API.Models.Entities.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Parking.ParkingSlot", b =>
                {
                    b.HasOne("EventParkingReservationSystem.API.Models.Entities.Events.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventParkingReservationSystem.API.Models.Entities.Parking.ParkingZone", "ParkingZone")
                        .WithMany("ParkingSlots")
                        .HasForeignKey("ParkingZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("ParkingZone");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Parking.ParkingZone", b =>
                {
                    b.HasOne("EventParkingReservationSystem.API.Models.Entities.Events.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.ParkingReservations.ParkingReservation", b =>
                {
                    b.HasOne("EventParkingReservationSystem.API.Models.Entities.Bookings.Booking", "Booking")
                        .WithOne("ParkingReservation")
                        .HasForeignKey("EventParkingReservationSystem.API.Models.Entities.ParkingReservations.ParkingReservation", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventParkingReservationSystem.API.Models.Entities.Parking.ParkingSlot", "ParkingSlot")
                        .WithMany()
                        .HasForeignKey("ParkingSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ParkingSlot");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Payments.Payment", b =>
                {
                    b.HasOne("EventParkingReservationSystem.API.Models.Entities.Bookings.Booking", null)
                        .WithOne()
                        .HasForeignKey("EventParkingReservationSystem.API.Models.Entities.Payments.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Seats.EventSeatCategory", b =>
                {
                    b.HasOne("EventParkingReservationSystem.API.Models.Entities.Events.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Seats.Seat", b =>
                {
                    b.HasOne("EventParkingReservationSystem.API.Models.Entities.Events.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventParkingReservationSystem.API.Models.Entities.Seats.SeatSection", "Section")
                        .WithMany("Seats")
                        .HasForeignKey("SeatSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Seats.SeatSection", b =>
                {
                    b.HasOne("EventParkingReservationSystem.API.Models.Entities.Events.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventParkingReservationSystem.API.Models.Entities.Seats.EventSeatCategory", "SeatCategory")
                        .WithMany("Sections")
                        .HasForeignKey("EventSeatCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("SeatCategory");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Bookings.Booking", b =>
                {
                    b.Navigation("BookingSeats");

                    b.Navigation("ParkingReservation");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Categories.EventCategory", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Parking.ParkingZone", b =>
                {
                    b.Navigation("ParkingSlots");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Seats.EventSeatCategory", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Seats.SeatSection", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("EventParkingReservationSystem.API.Models.Entities.Venues.Venue", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
